version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # golangci-lint
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.4
            sudo cp ./bin/golangci-lint $GOPATH/bin
      - run:
          name: Run tests
          command: make test
      - run:
          name: Lint
          command: make lint
