version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/xissy/kubeflake
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # godep
            curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
            dep ensure
            # golangci-lint
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.4
            sudo cp ./bin/golangci-lint $GOPATH/bin
      - run:
          name: Run tests
          command: make test
      - run:
          name: Lint
          command: make lint
